Hw09 struct validator
adrevin/ogdphw pull request #13
Opened 2023-05-16 06:56 UTC by adrevin

2023-05-17 16:47 UTC, dshemin requested changes

2023-05-17 16:47 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	for i := 0; i < rv.NumField(); i++ {
Важно:

Если v не структура - будет паника. Надо обязательно проверить что мы имеем дело именно со структурой.

2023-05-17 16:47 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		case
Важно:

Можно просто указать default в котором вернуть ошибку - не поддерживаемый тип

2023-05-17 16:47 UTC, dshemin commented on hw09_struct_validator/validator.go
> +			if slice, ok := value.Interface().([]string); ok {
Критично:

А для []int?

2023-05-17 16:47 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		// invalid tag, not processed
Важно:

Было бы неплохо уведомить программиста о том что он не верно указал тег. Иначе будут проблемы.

2023-05-17 16:47 UTC, dshemin commented on hw09_struct_validator/validator.go
> +				return nil
Важно:

Нельзя игнорировать ошибку.

2023-05-17 16:47 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		if len(ev) < 1 {
Важно:

Желательно всё же уведомить программиста что он неправильно пользуется вашим пакетом. Подобных мест очень много в Вашем коде, надо найти и обработать их все правильно. Основной смысл такой: если это ошибка - то это error. При этом внимательно посмотрите на задание, у нас есть ошибки валидации и программные ошибки и смешивать их нельзя.

2023-05-17 16:47 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		for _, s := range ev {
Важно:

Получается мы сначала разберём и распарсим строку в массив интов и потом пробежимся по нему. Итого у нас есть выделение памяти под слайс + 2 итерации. Можно сделать за одну итерацию и без выделения дополнительного слайса.

2023-05-17 16:47 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		inv := true
Важно:

Логика верная но смущает название переменной, я читаю ей как "присутствует в v" (in переводится как - в) а оно хранит состояние того, что строки НЕТ в v. Кажется надо подобрать более подходящее название.

2023-05-17 18:28 UTC, adrevin commented on hw09_struct_validator/validator.go
> +		case
https://github.com/adrevin/ogdphw/pull/13/commits/48121f113633af2ecfc1b26b7bcce5a675ad5b02

2023-05-17 18:39 UTC, adrevin commented on hw09_struct_validator/validator.go
> +			if slice, ok := value.Interface().([]string); ok {
и получилось
```
validator.go:58:3: missing cases in switch of type reflect.Kind: Invalid, Bool, Int8, Int16, Int32, Int64, Uint, Uint8, Uint16, Uint32, Uint64, Uintptr, Float32, Float64, Complex64, Complex128, Array, Chan, Func, Interface, Map, Pointer|Ptr, Struct, UnsafePointer (exhaustive)
                switch value.Kind() {
```
добавил https://github.com/adrevin/ogdphw/pull/13/commits/d3c9e0d7b2f0a1489efe2201ae50f6e6047e9150

2023-05-17 18:59 UTC, adrevin commented on hw09_struct_validator/validator.go
> +		case
и получилось все равно
```
validator.go:58:3: missing cases in switch of type reflect.Kind: Invalid, Bool, Int8, Int16, Int32, Int64, Uint, Uint8, Uint16, Uint32, Uint64, Uintptr, Float32, Float64, Complex64, Complex128, Array, Chan, Func, Interface, Map, Pointer|Ptr, Struct, UnsafePointer (exhaustive)
                switch value.Kind() {
```
добавил https://github.com/adrevin/ogdphw/pull/13/commits/d3c9e0d7b2f0a1489efe2201ae50f6e6047e9150

2023-05-19 09:46 UTC, adrevin commented on hw09_struct_validator/validator.go
> +		// invalid tag, not processed
https://github.com/adrevin/ogdphw/pull/13/commits/01996fe35326e3068da2c0cb665c59fb6232f4f2

2023-05-19 09:47 UTC, adrevin commented on hw09_struct_validator/validator.go
> +				return nil
https://github.com/adrevin/ogdphw/pull/13/commits/01996fe35326e3068da2c0cb665c59fb6232f4f2

2023-05-19 09:47 UTC, adrevin commented on hw09_struct_validator/validator.go
> +		if len(ev) < 1 {
https://github.com/adrevin/ogdphw/pull/13/commits/01996fe35326e3068da2c0cb665c59fb6232f4f2

2023-05-19 09:52 UTC, adrevin commented on hw09_struct_validator/validator.go
> +		inv := true
https://github.com/adrevin/ogdphw/pull/13/commits/6423da712821c6e522cb587c21182e25deabf091

2023-05-19 10:09 UTC, adrevin commented on hw09_struct_validator/validator.go
> +		for _, s := range ev {
https://github.com/adrevin/ogdphw/pull/13/commits/a030bfa13e517a9fb5899e2a3ba8635faf45d9b9

2023-05-20 00:49 UTC, dshemin approved these changes

2023-05-20 00:49 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	if reflect.TypeOf(v).Kind().String() != "struct" {
Важно:

Есть набор констант и лучше использовать их, чем преобразовывать к строке.

2023-05-20 00:49 UTC, dshemin commented on hw09_struct_validator/validator.go
> +				return &ValidationError{Field: f, Err: ErrInvalidTag}
Важно:

Я об этом предупреждал:

> Функция может возвращать
> - или программную ошибку, произошедшую во время валидации;
> - или `ValidationErrors` - ошибку, являющуюся слайсом структур, содержащих имя поля и ошибку его валидации.

То, что программист написал в коде не то, это не ошибка пользователя. Тут должна сразу вернутся ошибка, без добавления в слайс.

2023-05-20 00:49 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		// invalid tag, not processed
Важно:

В `validateIntField` это ошибка, тут тоже должна быть ошибка.

2023-05-21 09:31 UTC, adrevin commented on hw09_struct_validator/validator.go
> +	if reflect.TypeOf(v).Kind().String() != "struct" {
https://github.com/adrevin/ogdphw/pull/13/commits/cb7d39004365e2ca73b0321249ab11a72c11d57c

2023-05-21 11:13 UTC, adrevin commented on hw09_struct_validator/validator.go
> +				return &ValidationError{Field: f, Err: ErrInvalidTag}
https://github.com/adrevin/ogdphw/pull/13/commits/e1ae7aa10199a94c6153b2f9c8325bbc9476aad6
https://github.com/adrevin/ogdphw/pull/13/commits/9751ea92ba801987f73cf302b43d94368785519d

2023-05-21 11:13 UTC, adrevin commented on hw09_struct_validator/validator.go
> +		// invalid tag, not processed
https://github.com/adrevin/ogdphw/pull/13/commits/e1ae7aa10199a94c6153b2f9c8325bbc9476aad6
https://github.com/adrevin/ogdphw/pull/13/commits/9751ea92ba801987f73cf302b43d94368785519d

2023-05-21 18:54 UTC, dshemin approved these changes

2023-05-22 06:40 UTC, merged